#!/usr/bin/env bash
# The following bash script transfers a file from the client to a server

# Checking if all the required parameters are provided

# 1st setting the variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/school"

# 2nd checking the parameters
if [ $# -eq 2 ]; then
        scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
        echo -e "Usage: $filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

